name: Demo CI

on:
  pull_request:
    branches: [main]

jobs:
  demo-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run demo test
        run: echo "Demo test passed"
